### ISSUE TITLE
Using different labels

### ISSUE THREAD

**Issue by joshmyersdean** [berkeley-hipie/HIPIE#8]
Hello!

Thank you for this great work and I am looking forward to the training code release. In the meantime, is there an easy way to provide my own labels to the demo? Specifically part labels. 

Thank you!

**Comment by KKallidromitis** [comment]
Hi I have implemented a demo that uses a custom dataset ([Demo-HIPIE-custom.ipynb](https://github.com/berkeley-hipie/HIPIE/blob/main/notebooks/Demo-HIPIE-custom.ipynb)). Please note "stuff" must always be after "things" and also that the current model uses the standard weights and config so for optimal parts results please change to the parts model/config.

**Comment by joshmyersdean** [comment]
Amazing, thank you!

**Comment by joshmyersdean** [comment]
Hi again!

For custom parts, could you explain how you constructed the dictionary items in `get_args_eval()`? 

Thank you!

**Comment by KKallidromitis** [comment]
Hi, I am sorry for the delay. `get_args_eval()` is in the file `projects/HIPIE/hipie/demo_lib/demo_utils.py` it uses the `MetadataCatalog` from `detectron2` and the functions `get_openseg_labels,cat2ind_panoptics_coco`  from `projects/hipie/data/coco_dataset_mapper_uni.py` and  `projects/hipie/data/datasets/catids.py` respectively. 

For custom parts we dont explicitly call the function because it is used to load labels for existing datasets. For custom parts I imitate the format of labels in detectron by generating metadata using: `make_custom_metadata`. The function takes the custom labels as input and the metadata of `coco_2017_train_panoptic_with_sem_seg` for the color scheme.
